describe('test een', () =>{
    it('should visit productpage', function () {
        cy.visit("localhost:4200")
        cy.contains('Products').click()
        cy.url().should("eq", "http://localhost:4200/products")
        cy.contains('Show detail').click()
        cy.get('ul').should('exist')
        cy.url().should("eq", "http://localhost:4200/products/1")
    })
})

describe('test twee', () =>{
    it('should buy a product', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.contains('Products').click()
        cy.url().should("eq", "http://localhost:4200/products")
        cy.contains('Show detail').click()
        cy.get('ul').should('exist')
        cy.url().should("eq", "http://localhost:4200/products/1")
        cy.get('#1').click()
        cy.contains('Cart').click()
        cy.get('#orderButton').click()
    })
})

describe('test drie', () =>{
    it('should visit admin page', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.get('#dropdownMenu').click()
        cy.contains('Admin').click()
    })
})

describe('test vier', () =>{
    it('should add a product', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.get('#dropdownMenu').click()
        cy.contains('Admin').click()
        cy.contains('Add products').click()
        cy.get('#name').type('test')
        cy.get('#description').type('test')
        cy.get('#imagePath').type('test')
        cy.get('#category_id').select('1')
        cy.contains('Add product').click()
    })
})

describe('test vijf', () =>{
    it('should remove a product', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.get('#dropdownMenu').click()
        cy.contains('Admin').click()
        cy.contains('Remove products').click()
        cy.contains('Remove').click()
    })
})

describe('test zes', () =>{
    it('should remove a variant', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.get('#dropdownMenu').click()
        cy.contains('Admin').click()
        cy.contains('Remove products').click()
        cy.contains('Remove variant').click()
    })
})

describe('test zeven', () =>{
    it('should add variant stock', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.get('#dropdownMenu').click()
        cy.contains('Admin').click()
        cy.contains('Products stock').click()
        cy.get('#addOne').click()
    })
})

describe('test acht', () =>{
    it('should add variant', function () {
        cy.visit("localhost:4200")
        cy.get('#dropdownMenu').click()
        cy.contains('Login').click()
        cy.url().should("eq", "http://localhost:4200/account/login")
        cy.get('form').should('exist')
        cy.get('#email').type('bob@bobsluxuryenterprise.com')
        cy.get('#password1').type('Test123!')
        cy.get('#submit').click()
        cy.get('#dropdownMenu').click()
        cy.contains('Admin').click()
        cy.contains('Add products').click()
        cy.get('#product_id').select('1')
        cy.get('#size').type('test')
        cy.get('#material').type('test')
        cy.get('#color').type('test')
        cy.get('#price').type('1')
        cy.get('#addVar').click()
    })
})

